services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - /opt/movie-management-system-env/.env.postgres
    volumes:
      - /opt/movie-management-system-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.beta
    restart: always
    ports:
      - 127.0.0.1:8001:1923
    env_file:
      - /opt/movie-management-system-env/.env
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    container_name: gateway
    image: fholzer/nginx-brotli
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/nginx.beta.conf:/etc/nginx/conf.d/default.conf
      - /opt/letsencrypt:/etc/ssl
      - ./public:/var/www/public
    depends_on:
      - backend
    logging:
      options:
        max-size: "10m"
        max-file: "5"
