name: Beta Deployment

on:
  push:
    branches: [beta]

jobs:
  deploy-to-prod:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_BETA_HOST}}
          port: 22
          username: ${{secrets.SSH_BETA_USERNAME}}
          key: ${{secrets.SSH_BETA_KEY}}
          source: ".,!node_modules"
          target: "/opt/movie-management-system"
          rm: false

      - name: SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_BETA_HOST}}
          port: 22
          username: ${{secrets.SSH_BETA_USERNAME}}
          key: ${{secrets.SSH_BETA_KEY}}
          script: |
            cd /opt/movie-management-system
            bash scripts/start.beta.sh
